### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by MartinHerren**
Hej,

First many thanks for your work, your image works so much better than the official one. Running it on NVMe with u-boot on SPI.
My only issue is that with current kernel config it is not possible to run docker, that's why I'm investigating the missing set of options i require in the kernel to support it, and thus my PR.

2 little build improvements:
- make the build shell scripts executable
- accept a tmux environment instead of a screen one. The build script will still require screen to be installed, but will also build fine when running inside a tmux session

I don't want if you prefer the PR on the next branch. I won't take any offense if you don't want to merge it at all.

Thanks !

### CODE REVIEW

**Comment by luckylinux** [comment]
@MartinHerren I actually have the same problem (well podman, but probably a lot of kernel config options are shared with docker). See https://github.com/containers/netavark/issues/832. I was thinking of changing the make_kernel.sh script.

These are the logs I get, which show which kernel options appear to be missing
[docker-moby-check-config.log](https://github.com/inindev/rock-5b/files/13212462/docker-moby-check-config.log)
[runc-check-config.log](https://github.com/inindev/rock-5b/files/13212463/runc-check-config.log)


My current idea would be, after line `make -C "kernel-$lv/linux-$lv" ARCH=arm64 defconfig`, to add:
```
scripts/config --enable CONFIG_MEMCG_SWAP
scripts/config --enable CONFIG_BLK_DEV_THROTTLING
scripts/config --enable CONFIG_NET_CLS_CGROUP
scripts/config --enable CONFIG_CGROUP_NET_PRIO
scripts/config --enable CONFIG_CFS_BANDWIDTH
scripts/config --enable CONFIG_RT_GROUP_SCHED
scripts/config --enable CONFIG_IP_NF_TARGET_REDIRECT
scripts/config --enable CONFIG_IP_VS_NFCT
scripts/config --enable CONFIG_IP_VS_PROTO_TCP
scripts/config --enable CONFIG_IP_VS_PROTO_UDP
scripts/config --enable CONFIG_IP_VS_RR
scripts/config --enable CONFIG_SECURITY_SELINUX
scripts/config --enable CONFIG_SECURITY_APPARMOR
scripts/config --enable CONFIG_EXT3_FS_XATTR
scripts/config --enable CONFIG_EXT3_FS_POSIX_ACL
scripts/config --enable CONFIG_EXT3_FS_SECURITY
scripts/config --enable CONFIG_EXT4_FS_SECURITY
scripts/config --enable CONFIG_VXLAN
scripts/config --enable CONFIG_CRYPTO_SEQIV
scripts/config --enable CONFIG_XFRM
scripts/config --enable CONFIG_XFRM_USER
scripts/config --enable CONFIG_XFRM_ALGO
scripts/config --enable CONFIG_INET_ESP
scripts/config --enable CONFIG_NETFILTER_XT_MATCH_BPF
scripts/config --enable CONFIG_IPVLAN
scripts/config --enable CONFIG_DUMMY
scripts/config --enable CONFIG_NF_NAT_FTP
scripts/config --enable CONFIG_NF_CONNTRACK_FTP
scripts/config --enable CONFIG_NF_NAT_TFTP
scripts/config --enable CONFIG_NF_CONNTRACK_TFTP
scripts/config --enable CONFIG_NETFILTER_XT_MATCH_COMMENT # Not sure, this was about a "comment" error I got from netavark / iptables
```

I was actually about to do a fork & do it on my side, however I second the tmux idea :+1:.
Probably better to join forces ;).

uname -a
```
Linux Rock5B-01 6.6.0-rc4-1-arm64 #1 SMP PREEMPT Debian 6.6.0-rc4-1 (2023-10-01) aarch64 GNU/Linux
``

**Comment by luckylinux** [comment]
Optionally we could have an optional argument to make_kernel.sh (e.g. --enable-podman or --enable-docker), and only in that case those commands are executed. It should be default IMHO though.

**Comment by inindev** [comment]
Thanks for the contribution.  I am traveling this week so I have not gotten a chance to test this yet.  

For the config comment, I had thought that the config_fixups section could be for custom config to defconfig:
https://github.com/inindev/rock-5b/blob/main/kernel/make_kernel.sh#L11C1-L11C14

I have been working on the risc-v visionfive2 board recently and tried moving this function below the defconfig call:
https://github.com/inindev/visionfive2/blob/aedd15895416b2dfe966fd29c7717f821ab14ed3/kernel/make_kernel.sh#L77

This allowed me to use the ```scripts/config``` kernel script to edit the .config directly:
https://github.com/inindev/visionfive2/blob/aedd15895416b2dfe966fd29c7717f821ab14ed3/kernel/make_kernel.sh#L15

Thoughts on this as an approach here?

**Comment by luckylinux** [comment]
The approach seems OK to me. I'm not an expert though. I'd just like to get podman/docker running for now :+1:.

**I usually prefer to separate code/data**, therefore my approach would probably be to:
1. Keep your approach with a custom function call
2. Create a folder "profiles" (or whatever we want to call them)
3. In profiles we create a podman.config or docker.config based on what seems to be required (see my previous post), each of which contains the required custom kernel options / configuration
4. Your line `config_fixups "$lpath"` could be changed to something like (pseudo-code)
  ```
for each profile
config_profile "$lpath" "$profile"
end
```

And a switch --enable-docker and --enable-podman for make_kernel.sh. Or --podman=true and --docker=true or something similar.

In this way, we could also enable future custom configurations. E.g. custom graphics. Custom PCIe adapters (NIC, SAS, ...).

Note: "profiles" was just an example. It could be "custom", "userconfig", "feature" or whatever else.

**Comment by luckylinux** [comment]
In this way actually the profile file name could be used as a switch, therefore NOT requiring any re-coding of the script itself.

E.g. profiles/docker.config means "docker" profile and --docker switch

**Comment by MartinHerren** [comment]
> Thanks for the contribution. I am traveling this week so I have not gotten a chance to test this yet.
> 
> For the config comment, I had thought that the config_fixups section could be for custom config to defconfig: https://github.com/inindev/rock-5b/blob/main/kernel/make_kernel.sh#L11C1-L11C14
> 
> I have been working on the risc-v visionfive2 board recently and tried moving this function below the defconfig call: https://github.com/inindev/visionfive2/blob/aedd15895416b2dfe966fd29c7717f821ab14ed3/kernel/make_kernel.sh#L77
> 
> This allowed me to use the `scripts/config` kernel script to edit the .config directly: https://github.com/inindev/visionfive2/blob/aedd15895416b2dfe966fd29c7717f821ab14ed3/kernel/make_kernel.sh#L15
> 
> Thoughts on this as an approach here?

Having a VisionFive2 board, it is the next i will try of course ! Moving config_fixups after the defconfig call is definitively a cleaner way, instead of changing a 'source file', it patches a generated fail.

Maybe just an option to specify an alternative defconfig would be enough ?

**Comment by inindev** [comment]
> Maybe just an option to specify an alternative defconfig would be enough ?

I like this idea.

Also, do you even need ```tmnux``` at all?  I put ```screen``` in there as a reminder for myself -- I would forget to do so then realize 20 minutes into the build when I need to disconnect my ssh session.  i.e. would the better solution for docuker users be to bypass this check when docker is detected?

**Comment by luckylinux** [comment]
Well supporting multiple SBC is also a good idea. That's why a "profile" name (for which target board to use, similar to when rebuilding kernel for e.g. Raspberry PI) or "profiles" for **incremental** kernel config changes seem a good idea to me.

But my message about the required kernel options got totally ignored so far. So, if enabling the required docker/podman kernel options that I listed above is not adressed, I will just have to fork this repository and do a "split".

**Comment by inindev** [comment]
> Well supporting multiple SBC is also a good idea. That's why a "profile" name (for which target board to use, similar to when rebuilding kernel for e.g. Raspberry PI) or "profiles" for **incremental** kernel config changes seem a good idea to me.
> 
> But my message about the required kernel options got totally ignored so far. So, if enabling the required docker/podman kernel options that I listed above is not adressed, I will just have to fork this repository and do a "split".

The idea of having a custom config would be what would address this and seems like it would cover more use cases.  The ```kernel-$lv/linux-$lv/arch/arm64/configs/defconfig``` could be modified / patched, or a different config could be placed in this location and called by passing its name to the script.  This was people could submit kernel configs that accomplish higher-level goals like set-top-box, etc.

Thoughts?

**Comment by luckylinux** [comment]
> > Well supporting multiple SBC is also a good idea. That's why a "profile" name (for which target board to use, similar to when rebuilding kernel for e.g. Raspberry PI) or "profiles" for **incremental** kernel config changes seem a good idea to me.
> > But my message about the required kernel options got totally ignored so far. So, if enabling the required docker/podman kernel options that I listed above is not adressed, I will just have to fork this repository and do a "split".
> 
> The idea of having a custom config would be what would address this and seems like it would cover more use cases. The `kernel-$lv/linux-$lv/arch/arm64/configs/defconfig` could be modified / patched, or a different config could be placed in this location and called by passing its name to the script. This way people could submit kernel configs that accomplish higher-level goals like set-top-box, etc.
> 
> Thoughts?

Well, maybe things have changed since I was used to compile kernels every day (Gentoo - long story).

The way I understood/understand is:
- `make defconfig` will ALWAYS generate the default configuration for the selected/targeted platform. **No matter kernel version**. So we don't need to have a version 6.5 kernel defconfig, version 6.6 kernel defconfig, ...
- My incremental-differential approach / profiles is just trying to select the required features that ones want **on top** of the default configuration. Provided the parameters do not change between Kernel Versions, the incremental-differential approach could apply to (practically) all kernel versions. Since anyway `defconfig` would take care of that part
- That's why I am reluctant on patching a defconfig. It's manual work. I would just prefer to call a set of script AFTER defconfig has done its job

And my previous ideas of profiles/docker.config might also be profiles/docker.sh. It all depends if you want to put the kernel configuration lines there (in which case you might also potentially just use a .patch file), or a set of commands to execute to update the configuration.

For the sake of clarify, my previous profiles/docker.config idea would have been more towards the **command** approach. Maybe my .config extension was misleading, sorry about that.

profiles/docker.sh
```
scripts/config --enable CONFIG_MEMCG_SWAP
scripts/config --enable CONFIG_BLK_DEV_THROTTLING
scripts/config --enable CONFIG_NET_CLS_CGROUP
scripts/config --enable CONFIG_CGROUP_NET_PRIO
scripts/config --enable CONFIG_CFS_BANDWIDTH
scripts/config --enable CONFIG_RT_GROUP_SCHED
scripts/config --enable CONFIG_IP_NF_TARGET_REDIRECT
scripts/config --enable CONFIG_IP_VS_NFCT
scripts/config --enable CONFIG_IP_VS_PROTO_TCP
scripts/config --enable CONFIG_IP_VS_PROTO_UDP
scripts/config --enable CONFIG_IP_VS_RR
scripts/config --enable CONFIG_SECURITY_SELINUX
scripts/config --enable CONFIG_SECURITY_APPARMOR
scripts/config --enable CONFIG_EXT3_FS_XATTR
scripts/config --enable CONFIG_EXT3_FS_POSIX_ACL
scripts/config --enable CONFIG_EXT3_FS_SECURITY
scripts/config --enable CONFIG_EXT4_FS_SECURITY
scripts/config --enable CONFIG_VXLAN
scripts/config --enable CONFIG_CRYPTO_SEQIV
scripts/config --enable CONFIG_XFRM
scripts/config --enable CONFIG_XFRM_USER
scripts/config --enable CONFIG_XFRM_ALGO
scripts/config --enable CONFIG_INET_ESP
scripts/config --enable CONFIG_NETFILTER_XT_MATCH_BPF
scripts/config --enable CONFIG_IPVLAN
scripts/config --enable CONFIG_DUMMY
scripts/config --enable CONFIG_NF_NAT_FTP
scripts/config --enable CONFIG_NF_CONNTRACK_FTP
scripts/config --enable CONFIG_NF_NAT_TFTP
scripts/config --enable CONFIG_NF_CONNTRACK_TFTP
scripts/config --enable CONFIG_NETFILTER_XT_MATCH_COMMENT # Not sure, this was about a "comment" error I got from netavark / iptables
```

**Comment by inindev** [comment]
this line: https://github.com/inindev/rock-5b/blob/main/kernel/make_kernel.sh#L67C9-L67C16

says to build a ```.config``` from ```kernel-$lv/linux-$lv/arch/arm64/configs/defconfig```

if you put your own file in this directory: ```kernel-$lv/linux-$lv/arch/arm64/configs/my_defconfig```

you could call it via:

```make -C "kernel-$lv/linux-$lv" ARCH=arm64 my_defconfig```

**Comment by inindev** [comment]
Another approach would be to modify the defconfig itself:

```
config_fixups() {
    echo CONFIG_MEMCG_SWAP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_BLK_DEV_THROTTLING >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NET_CLS_CGROUP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_CGROUP_NET_PRIO >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_CFS_BANDWIDTH >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_RT_GROUP_SCHED >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IP_NF_TARGET_REDIRECT >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IP_VS_NFCT >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IP_VS_PROTO_TCP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IP_VS_PROTO_UDP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IP_VS_RR >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_SECURITY_SELINUX >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_SECURITY_APPARMOR >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_EXT3_FS_XATTR >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_EXT3_FS_POSIX_ACL >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_EXT3_FS_SECURITY >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_EXT4_FS_SECURITY >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_VXLAN >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_CRYPTO_SEQIV >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_XFRM >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_XFRM_USER >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_XFRM_ALGO >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_INET_ESP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NETFILTER_XT_MATCH_BPF >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_IPVLAN >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_DUMMY >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NF_NAT_FTP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NF_CONNTRACK_FTP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NF_NAT_TFTP >> "$lpath/arch/arm64/configs/defconfig"
    echo CONFIG_NF_CONNTRACK_TFTP >> "$lpath/arch/arm64/configs/defconfig"
    # Not sure, this was about a "comment" error I got from netavark / iptables
    echo CONFIG_NETFILTER_XT_MATCH_COMMENT >> "$lpath/arch/arm64/configs/defconfig"
}
```

**Comment by luckylinux** [comment]
> this line: https://github.com/inindev/rock-5b/blob/main/kernel/make_kernel.sh#L67C9-L67C16
> 
> says to build a `.config` from `kernel-$lv/linux-$lv/arch/arm64/configs/defconfig`
> 
> if you put your own file in this directory: `kernel-$lv/linux-$lv/arch/arm64/configs/my_defconfig`
> 
> you could call it via:
> 
> `make -C "kernel-$lv/linux-$lv" ARCH=arm64 my_defconfig`

But again, this requires me to provide the full .config. Which is not what I want / suggest. More tricky to maintain between kernel updates, not modular at all, etc.

**Comment by luckylinux** [comment]
> Another approach would be to modify the defconfig itself:
> 
> ```
> config_fixups() {
>     echo CONFIG_MEMCG_SWAP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_BLK_DEV_THROTTLING >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NET_CLS_CGROUP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_CGROUP_NET_PRIO >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_CFS_BANDWIDTH >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_RT_GROUP_SCHED >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IP_NF_TARGET_REDIRECT >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IP_VS_NFCT >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IP_VS_PROTO_TCP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IP_VS_PROTO_UDP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IP_VS_RR >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_SECURITY_SELINUX >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_SECURITY_APPARMOR >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_EXT3_FS_XATTR >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_EXT3_FS_POSIX_ACL >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_EXT3_FS_SECURITY >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_EXT4_FS_SECURITY >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_VXLAN >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_CRYPTO_SEQIV >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_XFRM >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_XFRM_USER >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_XFRM_ALGO >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_INET_ESP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NETFILTER_XT_MATCH_BPF >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_IPVLAN >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_DUMMY >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NF_NAT_FTP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NF_CONNTRACK_FTP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NF_NAT_TFTP >> "$lpath/arch/arm64/configs/defconfig"
>     echo CONFIG_NF_CONNTRACK_TFTP >> "$lpath/arch/arm64/configs/defconfig"
>     # Not sure, this was about a "comment" error I got from netavark / iptables
>     echo CONFIG_NETFILTER_XT_MATCH_COMMENT >> "$lpath/arch/arm64/configs/defconfig"
> }
> ```

Sure :). This would be the "quick&dirty fix". I was trying to provide an idea that would scale up in the future, if other people wanted other features. To solve the problem (for me and @MartinHerren ), this is probably sufficient. But then again, we start to need modifying files each time we do a git clone or every time somebody else wants something else.

That's why I suggested to just load some "modular" blocks of configuration on top of the defconfig, so everybody can get what they want (if they want it), it's easier to test and expand (just create a new file) and we can keep a unified codebase :).

**Comment by inindev** [comment]
> That's why I suggested to just load some "modular" blocks of configuration on top of the defconfig, so everybody can get what they want (if they want it), it's easier to test and expand (just create a new file) and we can keep a unified codebase :).

Wouldn't this just be:

```
config_fixups() {
    local lpath="$1"

    cat my_defconfig_fixups.txt >> "$lpath/arch/arm64/configs/defconfig"
}
```

In the script as it exists now?  You do you mean the script would allow you to specify a ```my_defconfig_fixups.txt``` command line parameter?

**Comment by luckylinux** [comment]
> > That's why I suggested to just load some "modular" blocks of configuration on top of the defconfig, so everybody can get what they want (if they want it), it's easier to test and expand (just create a new file) and we can keep a unified codebase :).
> 
> Wouldn't this just be:
> 
> ```
> config_fixups() {
>     local lpath="$1"
> 
>     cat my_defconfig_fixups.txt >> "$lpath/arch/arm64/configs/defconfig"
> }
> ```
> 
> In the script as it exists now?
> 
> Or do you mean the script would allow you to specify a `my_defconfig_fixups.txt` command line parameter?

Essentially yes.

But I have no idea if it works as intended, in case defconfig now contains two conflicting lines (the one from "defconfig" and the one that I try to override). Will the "second occurrence" in defconfig take priority ?

That's why I suggested a script, to use script/config too to **override** some very specific default kernel configuration.

The idea I originally had was to specify a --docker=true or --podman=true (or false). So you'd need to dynamically parse all arguments provided to make_kernel.sh, and if a file with that name exist in profiles/*.sh (profiles/docker.sh or profiles/podman.sh) and the value is set to true, then it executes it to update the default kernel configuration.

But don't only focus on this example. Implement in a generic way. That way we can always add a new file. And combine all required options.

Example: ./make_kernel.sh --podman=true --docker=true --gpu=true ....

(maybe =true / =false not needed and we can only use ./make_kernel.sh --podman --docker --gpu ....)

Maybe "features" is a better name rather than "profiles". Not sure.

**Comment by inindev** [comment]
I see, that would be nice. 

It looks like ```scripts/config``` accepts a ```--file``` parameter which would allow defconfig to be modified for feature removals.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/config?h=v6.6

**Comment by luckylinux** [comment]
I'm not a BASH expert, but it might be that getopts might be too complicated, especially if you don't know the name of the feature "a priori".

Maybe it would be easier, to keep CODE and CONFIGURATION separate to just:
- Have make_kernel.sh without any argument call features.sh, non-user configurable
- Have features.sh indicate which features to load (e.g. `features/docker.sh`), user-configurable

**Comment by luckylinux** [comment]
Or maybe an approach similar to what APACHE web server does ?

Put all optional "modules" or "features" in mods-available, and let the user select them by symlinking them ?

- Available in `mods-available`
- Enabled in `mods-enabled`

Probably much easier to implement from a development point of view. Just load all the scripts contained/linked in `mods-enabled`. Not sure from a user perspective ...

**Comment by luckylinux** [comment]
I tried to fork to try some changes. https://github.com/luckylinux/rock-5b/tree/main/kernel

I tried the script approach. It works. Maybe the config approach would be better/easier.

The echo >> defconfig needs to be improved, since if the script is executed multiple times, multiple entries are added to the configuration file, which triggers warnings.

Unfortunately the generated kernel (6.6.0) does NOT boot from microSD, whereas your generated kernel (6.6 rc4) boots correctly from microSD.

Are you aware of gcc-13 being REQUIRED explicitely ? I had to compile using gcc-12 since I downgraded to Debian 12 Bookworm.

I got the 4 .debs generated correctly and installed. But the blue light doesn't flash indicating no boot.

**Comment by inindev** [comment]
>> Are you aware of gcc-13 being REQUIRED explicitely ? I had to compile using gcc-12 since I downgraded to Debian 12 Bookworm.

Thank you, this is definitely a bug on my part.

```CC='gcc-13'```

It should be: ```CC="$(readlink /usr/bin/gcc)"```

**Comment by luckylinux** [comment]
> > > Are you aware of gcc-13 being REQUIRED explicitely ? I had to compile using gcc-12 since I downgraded to Debian 12 Bookworm.
> 
> Thank you, this is definitely a bug on my part.
> 
> `CC='gcc-13'`
> 
> It should be:
> 
> `CC="$(readlink /usr/bin/gcc)"`
> 
> (or omit it)

I just used CC="gcc", so it will pick system's default anyway.

I'm not sure why my kernel doesn't boot. I cannot get HDMI output either way, so difficult to tell. How do you even debug on this board ? Serial debugging using an RS232-TTL adapter ?

Could you try with the updates I pushed to my fork and see if it works on your side ? I don't think it's worth to do a PR yet. Or should I just do that ?

https://github.com/luckylinux/rock-5b/tree/main/kernel

**Comment by luckylinux** [comment]
Actually serial debugging was quite easy and I got some useful logs.

Howto
https://wiki.radxa.com/Rock5/dev/serial-console

Logs
[rock5_6.6.0_no_ethernet_no_nvme.log](https://github.com/inindev/rock-5b/files/13223170/rock5_6.6.0_no_ethernet_no_nvme.log)
[rock5_6.6rc4_ethernet_nvme.log](https://github.com/inindev/rock-5b/files/13223171/rock5_6.6rc4_ethernet_nvme.log)


With @inindev kernel (got it from latest Debian Trixie image, then downgraded to Debian Bookworm using APT Pinning method) I can successfully boot. PCIe works, NVMe works, Ethernet works.

With the kernel I build, no PCIe, no NVMe, no Ethernet.

Ideas ?

**Comment by inindev** [comment]
>With the kernel I build, no PCIe, no NVMe, no Ethernet.
>
>Ideas ?

I am stuck out-of-town for work until Saturday, so I wont have access to any of my hardware to run hands-on scenarios.  I expect to be able to look at this more closely at that point.

I can offer than my role in this is roll-up distro is that of aggregating and testing patches as they move largely from (Sebastian Reichel's fork)[https://git.kernel.org/pub/scm/linux/kernel/git/sre/linux-misc.git/log/?h=rk3588] to upstream.
--

**Comment by luckylinux** [comment]
Fair enough. I'm also not a kernel dev. And it's not necessarily up to you to solve "my problems". Although I think that could also interest @MartinHerren (for the Docker part).

It's just weird because I'm only enabling some extra options in the kernel.

That being said, I could NEVER get anything to boot properly so that I could access it over SSH, if I built it myself. Tried kernel 6.5.9 and kernel 6.6-rc4, kernel 6.6-rc7 etc.

So technically it does boot, it's "just" that nothing works.

@MartinHerren: are you on Debian Bookworm or Debian Trixie ? Would you mind trying to build using the options I provided, and see if you could get your build to boot (with Ethernet, NVMe, PCIe) ? In my case I am using SD boot as it's easier to fix in case things go wrong (pull out SD card and update /boot/extlinux/extlinux.conf and change default option). Although, with Serial debugging, NVMe would also work (you can always select the older kernel during the bootloader prompt).

**Comment by luckylinux** [comment]
I am trying again with Linux 6.5.9 kernel now. I see that now I got prompted, after applying my Docker/Podman config, to answer some questions for the sub-modules. I just accepted the defaults for now. That's at least a change compared to what I had with Linux 6.6. Or maybe because I did a "clean start" of the download archive + configure process.

**Comment by luckylinux** [comment]
Same result. Something doesn't seem right. Nothing works if I build the kernel.

This is the Kernel .config for 6.5.9
[kernel-6.5.9.config.txt](https://github.com/inindev/rock-5b/files/13224828/kernel-6.5.9.config.txt)

**Comment by inindev** [comment]
The approach I take when looking for the result of CONFIG_ changes is to use the menu then distill them back to a defconfig.  

For example:
```
cd linux-6.6
make ARCH=arm64 defconfig
make ARCH=arm64 menuconfig
* make edits
* note that using slash / you can search for the location of config constants 
make ARCH=arm64 savedefconfig
diff defconfig arch/arm64/configs/defconfig
```

**Comment by luckylinux** [comment]
> The approach I take when looking for the result of a CONFIG_ change is to use the menu then distill them back to a defconfig.
> 
> For example:
> 
> ```
> cd linux-6.6
> make ARCH=arm64 defconfig
> make ARCH=arm64 menuconfig
> * make edits
> * note that using slash / you can search for the location of config constants 
> make ARCH=arm64 savedefconfig
> diff defconfig arch/arm64/configs/defconfig
> ```

I'm not sure if things have changed, but ever since I used linux I did

```
make defconfig
make olddefconfig # when updating from a previous Kernel Config
make menuconfig
```

However, after you call `make defconfig` and the arch/arm64/configs/defconfig (modified by you or "vanilla") gets "loaded" and transferred to .config, any further update (using `make menuconfig` or manual) will need to be applied to `.config`, not `arch/arm64/configs/defconfig` ! It also states that clearly in the console when you run ./make_kernel.sh.

That's also why I was a bit confused at first, because `make defconfig` for me is a "built-in" command of the Kernel Source, not a file I would work on. You might work on it, but I don't know if anybody recommends it.

**Comment by inindev** [comment]
I am usually more successful making changes in the menu UI rather than using individual text settings.  I also wanted to point out these defconfigs are generated using ```savedefconfig``` which produces a file named ```defconfig``` in the current directory.  Renaming this file to foo_defconfig and copying it to ```arch/arm64/configs/defconfig``` allows you to call it from make: ```make foo_defconfig```

**Pull request merged**
